In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
a


tensor([[3.3560e-13, 4.3978e-41, 3.3560e-13],
        [4.3978e-41, 0.0000e+00, 0.0000e+00]])

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(6,3)

tensor([[0.3649, 0.5029, 0.6586],
        [0.3645, 0.4138, 0.7363],
        [0.1221, 0.9953, 0.6107],
        [0.8787, 0.7295, 0.0126],
        [0.5810, 0.7159, 0.3015],
        [0.7919, 0.9774, 0.3669]])

In [ ]:
# manual_seed
torch.manual_seed(500)
torch.rand(2,3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [ ]:
torch.manual_seed(500)
torch.rand(4,5)

tensor([[0.5820, 0.1338, 0.7995, 0.3071, 0.6526],
        [0.6105, 0.1575, 0.6983, 0.7883, 0.7981],
        [0.4593, 0.8997, 0.2518, 0.5648, 0.0302],
        [0.5930, 0.6386, 0.4795, 0.6030, 0.7351]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,7))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

Creating tensors in different ways
torch.tensor([[1,2,3],[4,5,6]])


Creates a tensor from a Python list.
Shape → (2, 3) (2 rows, 3 columns).

torch.arange(0, 10, 2)


Creates numbers from 0 to 10 (excluding 10) with a step of 2.
Output → 0, 2, 4, 6, 8
Useful when you want evenly spaced values like loops.

torch.linspace(0, 10, 10)


Creates 10 equally spaced values between 0 and 10 (including both).
Useful in math, plotting, and ML experiments.

torch.eye(5)


Creates a 5 × 5 identity matrix
Diagonal values = 1, rest = 0
Very useful in linear algebra.

torch.full((3, 3), 5)


Creates a 3 × 3 tensor filled with 5
Good when you want constant values.

Tensor shape
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape


Output → torch.Size([2, 3])
Means 2 rows and 3 columns.

Creating tensors with the same shape as another tensor
torch.empty_like(x)


Creates a tensor with same shape as x, but values are random garbage (uninitialized).
Fast, but values are meaningless.

torch.zeros_like(x)


Creates a tensor with same shape as x, filled with 0s.

torch.ones_like(x)


Creates a tensor with same shape as x, filled with 1s.

torch.rand_like(x, dtype=torch.float32)


Creates a tensor with same shape as x, filled with random values between 0 and 1, and data type set to float32.



In [ ]:
  x = torch.tensor([[7,2,3],[4,5,6]])
  x

tensor([[7, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[        0, 327445728,         0],
        [        0,         0,         0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.7602, 0.8872, 0.8153],
        [0.2794, 0.0168, 0.6273]])

## Tensor Data Types

In [ ]:
# find data type formate : "name of tensor.dtype"
x.dtype

torch.int64

In [ ]:
# assign data type (changes the data type from one to another or can say forces)
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[7., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.6037, 0.1817],
        [0.3849, 0.8164]])

In [ ]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.3644, 0.0330],
        [0.1482, 0.6665]])

### 2. Element wise operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3086, 0.4626, 0.7494],
        [0.9410, 0.0619, 0.6229]])
tensor([[0.8790, 0.6113, 0.6402],
        [0.0360, 0.4153, 0.2534]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3086, 0.4626, 0.1091],
        [0.0048, 0.0619, 0.1161]])

In [ ]:
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 1., 9.],
        [1., 9., 2.]])

In [ ]:
torch.sum(e, dim=0)

tensor([ 3., 10., 11.])

In [ ]:
# sum
torch.sum(e)
# sum along columns

# sum along rows


tensor(24.)

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([1.5000, 5.0000, 5.5000])

In [ ]:
# median
torch.median(e)

tensor(2.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [ ]:
# product
torch.prod(e)

tensor(324.)

In [ ]:
# standard deviation
torch.std(e)

tensor(3.8987)

In [ ]:
# variance
torch.var(e)

tensor(15.2000)

In [ ]:
# argmax
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [ ]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 1, 7],
        [7, 9, 9]])
tensor([[7, 9],
        [2, 5],
        [3, 4]])


In [ ]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 51,  69],
        [ 94, 144]])

In [ ]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 7],
        [1, 9],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 9., 6.],
        [2., 8., 7.],
        [1., 2., 8.]])

In [ ]:
# determinant
torch.det(h)

tensor(-55.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.9091,  1.0909, -0.2727],
        [ 0.1636, -0.0364, -0.0909],
        [ 0.0727, -0.1273,  0.1818]])

### 5. Comparison operations

In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 3, 0],
        [8, 0, 4]])
tensor([[2, 2, 7],
        [9, 7, 0]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[1., 4., 3.],
        [4., 6., 1.]])

In [ ]:
# log
torch.log(k)

tensor([[0.0000, 1.3863, 1.0986],
        [1.3863, 1.7918, 0.0000]])

In [ ]:
# exp
torch.exp(k)

tensor([[  2.7183,  54.5981,  20.0855],
        [ 54.5981, 403.4288,   2.7183]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.0000, 1.7321],
        [2.0000, 2.4495, 1.0000]])

In [ ]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(k)

tensor([[0.7311, 0.9820, 0.9526],
        [0.9820, 0.9975, 0.7311]])

In [ ]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(k, dim=0)

tensor([[0.0474, 0.1192, 0.8808],
        [0.9526, 0.8808, 0.1192]])

In [ ]:
# relu


## Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9695, 0.5142, 0.5998],
        [0.1723, 0.0430, 0.7949]])
tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])


In [ ]:
m.add_(n)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [ ]:
m

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [ ]:
n

tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])

In [ ]:
torch.relu(m)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [ ]:
m.relu_()

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [ ]:
m

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
id(a)

134788465262912

In [ ]:
id(b)

134788465262912

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.6978,  0.4469],
        [ 0.7157,  0.8856,  0.0561]])

In [ ]:
b

tensor([[0.0000, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])

In [ ]:
id(a)

134788465262912

In [ ]:
id(b)

134788465269952

In [ ]:
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
a.shape

torch.Size([3, 3])

In [ ]:
b = torch.empty_like(a)
b


tensor([[134793970642320,       351742288,               0],
        [              0,               0,               0],
        [              0,               0,               0]])